services:
  mvcgridproject:
    image: mvcgridproject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - mvcgrid_data:/app/data
      - key_data:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
    networks:
      - mvcgrid_network

networks:
  mvcgrid_network:
    driver: bridge

volumes:
  mvcgrid_data:
  key_data:
