# Variables and secrets used in this workflow:
# - VPS_SSH_KEY: SSH key for accessing the VPS (secret)
# - VPS_HOST: Hostname or IP address of the VPS (variable)
# - VPS_USER: Username for SSH access to the VPS (variable)
# - VPS_REPO_DIR: Directory of the repository on the VPS (variable)

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Save commit hash
      if: success()
      run: echo ${{ github.sha }} > commit_hash.txt

    - name: Upload commit hash
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: commit-hash
        path: commit_hash.txt

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH key
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$VPS_SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -v -H ${{ vars.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Debug SSH connection
      run: ssh -v ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} 'echo "SSH connection successful"'

    - name: Copy files to VPS
      run: scp -r . ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }}:${{ vars.VPS_REPO_DIR }}/

    - name: Deploy to VPS
      run: |
        ssh ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} '
          cd ${{ vars.VPS_REPO_DIR }}
          docker-compose build
          docker-compose up -d
        '

  rollback:
    needs: [build-and-test, deploy]
    runs-on: ubuntu-latest
    if: failure()

    steps:
    - uses: actions/checkout@v2

    - name: Download commit hash
      uses: actions/download-artifact@v3
      with:
        name: commit-hash

    - name: Get last working commit
      run: echo "LAST_WORKING_COMMIT=$(cat commit_hash.txt)" >> $GITHUB_ENV

    - name: Checkout last working commit
      uses: actions/checkout@v2
      with:
        ref: ${{ env.LAST_WORKING_COMMIT }}

    - name: Copy rollback files to VPS
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      run: |
        echo "$VPS_SSH_KEY" > vps_ssh_key
        chmod 600 vps_ssh_key
        scp -i vps_ssh_key -o StrictHostKeyChecking=no -r . ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }}:${{ vars.VPS_REPO_DIR }}_rollback/
        rm vps_ssh_key

    - name: Deploy rollback to VPS
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      run: |
        echo "$VPS_SSH_KEY" > vps_ssh_key
        chmod 600 vps_ssh_key
        ssh -i vps_ssh_key -o StrictHostKeyChecking=no ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} '
          cd ${{ vars.VPS_REPO_DIR }}_rollback
          docker-compose build
          docker-compose up -d
        '
        rm vps_ssh_key